/*
  This file is dynamically generated. Edit ../genIcons.js instead
*/
import fontawesome from '@fortawesome/fontawesome'
fontawesome.config.autoAddCss = false
import faUser from '@fortawesome/fontawesome-free-solid/faUser'
import faIdCard from '@fortawesome/fontawesome-free-solid/faIdCard'
import faEnvelope from '@fortawesome/fontawesome-free-solid/faEnvelope'
import faChevronLeft from '@fortawesome/fontawesome-free-solid/faChevronLeft'
import faChevronRight from '@fortawesome/fontawesome-free-solid/faChevronRight'
import faChevronUp from '@fortawesome/fontawesome-free-solid/faChevronUp'
import faGlobe from '@fortawesome/fontawesome-free-solid/faGlobe'
import faUserCircle from '@fortawesome/fontawesome-free-solid/faUserCircle'
import faSearch from '@fortawesome/fontawesome-free-solid/faSearch'
import faCaretDown from '@fortawesome/fontawesome-free-solid/faCaretDown'
import faLock from '@fortawesome/fontawesome-free-solid/faLock'
import faEye from '@fortawesome/fontawesome-free-solid/faEye'
import faEyeSlash from '@fortawesome/fontawesome-free-solid/faEyeSlash'
import faFile from '@fortawesome/fontawesome-free-solid/faFile'
import faHome from '@fortawesome/fontawesome-free-solid/faHome'
import faBullhorn from '@fortawesome/fontawesome-free-solid/faBullhorn'
import faCalendarAlt from '@fortawesome/fontawesome-free-solid/faCalendarAlt'
import faFileAlt from '@fortawesome/fontawesome-free-solid/faFileAlt'
import faExternalLinkAlt from '@fortawesome/fontawesome-free-solid/faExternalLinkAlt'
import faHandshake from '@fortawesome/fontawesome-free-solid/faHandshake'
import faCog from '@fortawesome/fontawesome-free-solid/faCog'
import faTrash from '@fortawesome/fontawesome-free-solid/faTrash'
import faEllipsisV from '@fortawesome/fontawesome-free-solid/faEllipsisV'
import faFilePdf from '@fortawesome/fontawesome-free-solid/faFilePdf'
import faFileWord from '@fortawesome/fontawesome-free-solid/faFileWord'
import faFileExcel from '@fortawesome/fontawesome-free-solid/faFileExcel'
import faFilePowerpoint from '@fortawesome/fontawesome-free-solid/faFilePowerpoint'
import faDownload from '@fortawesome/fontawesome-free-solid/faDownload'
import faUserPlus from '@fortawesome/fontawesome-free-solid/faUserPlus'
import faExclamationCircle from '@fortawesome/fontawesome-free-solid/faExclamationCircle'
import faList from '@fortawesome/fontawesome-free-solid/faList'
import faUsers from '@fortawesome/fontawesome-free-solid/faUsers'
import faUndo from '@fortawesome/fontawesome-free-solid/faUndo'
import faPencilAlt from '@fortawesome/fontawesome-free-solid/faPencilAlt'
import faFacebookSquare from '@fortawesome/fontawesome-free-brands/faFacebookSquare'
import faTwitterSquare from '@fortawesome/fontawesome-free-brands/faTwitterSquare'
import faPinterestSquare from '@fortawesome/fontawesome-free-brands/faPinterestSquare'
import faInstagram from '@fortawesome/fontawesome-free-brands/faInstagram'
import faYoutube from '@fortawesome/fontawesome-free-brands/faYoutube'
fontawesome.library.add(faUser, faIdCard, faEnvelope, faChevronLeft, faChevronRight, faChevronUp, faGlobe, faUserCircle, faSearch, faCaretDown, faLock, faEye, faEyeSlash, faFile, faHome, faBullhorn, faCalendarAlt, faFileAlt, faExternalLinkAlt, faHandshake, faCog, faTrash, faEllipsisV, faFilePdf, faFileWord, faFileExcel, faFilePowerpoint, faDownload, faUserPlus, faExclamationCircle, faList, faUsers, faUndo, faPencilAlt, faFacebookSquare, faTwitterSquare, faPinterestSquare, faInstagram, faYoutube)