const users = require('./users/users.service.js')
const posts = require('./posts/posts.service.js')
const comments = require('./comments/comments.service.js')
const pages = require('./pages/pages.service.js')
const avatars = require('./avatars/avatars.service.js')
const restricts = require('./restricts/restricts.service.js')
const contact = require('./contact/contact.service.js')
const resources = require('./resources/resources.service.js')
const opps = require('./opps/opps.service.js')
const oppsCats = require('./opps-cats/opps-cats.service.js')
const pageThumbs = require('./page-thumbs/page-thumbs.service.js')
const mods = require('./mods/mods.service.js')
module.exports = function() {
  const app = this // eslint-disable-line no-unused-vars
  app.configure(users)
  app.configure(posts)
  app.configure(comments)
  app.configure(pages)
  app.configure(avatars)
  app.configure(restricts)
  app.configure(contact)
  app.configure(resources)
  app.configure(opps)
  app.configure(oppsCats)
  app.configure(pageThumbs)
  app.configure(mods)
}
